### PR TITLE
Fixing the Repo

### PR DESCRIPTION
**Pull request by ludusrusso**
I'm not sure if this solved issue #71 since I cannot test it locally!
Test it!

### CODE REVIEW

**Comment by gmacario** [comment]
Thanks @ludusrusso will do as soon as I finish to reinstall the prerequisite packages on my brand new laptop :wink:

**Comment by gmacario** [comment]
Hi @ludusrusso,

I am trying your PR locally on a brand new Ubuntu 16.04.3 LTS machine where I have done `sudo apt install jekyll`. Here is the result:

```
gmacario@itm-gmacario-w7:~/github/gmacario/gmacario.github.io (ludusrusso-master)$ jekyll serve
Configuration file: /home/gmacario/github/gmacario/gmacario.github.io/_config.yml
            Source: /home/gmacario/github/gmacario/gmacario.github.io
       Destination: /home/gmacario/github/gmacario/gmacario.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
     Build Warning: Layout 'post' requested in _posts/2015-01-20-welcome-to-jekyll.markdown does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-01-21-my-first-post.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-02-28-first-experiments-with-arduino-yun.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-03-22-inspecting-yun-linux-configuration.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-03-27-preparing-my-yun-for-the-arduino-day.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-03-28-workshop-arduino-pro.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-03-30-upgrading-openwrt-on-my-yun.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-04-11-notes-from-cyanogenmod-workshop-at-it-droidcon-2015.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-04-15-using-jekyll-with-pages.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-04-18-trying-android-studio.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-04-19-trying-genymotion.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-04-23-building-genivi-demo-platform.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-10-17-heading-to-genivi-13th-amm.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-11-07-searching-for-files-in-ubuntu-packages.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-11-08-connecting-to-udoo-neo-serial-console.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-11-12-trying-yocto-on-udoo-neo.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-11-14-running-yocto-image-inside-virtualbox.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-11-15-installing-terminator-on-ubuntu-1404.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-11-22-building-yocto-for-udooneo.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-11-29-install-openwrt-on-kingston-mlwg2.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-12-10-testing-rancheros.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2016-01-06-trying-openelec-on-raspberry-pi2.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2016-01-08-installing-dlt-viewer-on-windows.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2016-04-01-continuous-delivery-using-docker-and-jenkins.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2016-06-08-webapps-embsys-jsnight.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2016-12-23-trying-gdp11-on-rpi3.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2017-01-19-trying-kali-2.1.2-on-rpi3.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2017-03-03-restoring-arduino-yun-factory-settings.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2017-03-14-trying-chip.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2017-03-31-trying-volumio-on-rpi3.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2017-05-15-trying-gdp-master-raspberrypi3.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2017-06-24-neopixel-led-strips-for-expo-mattoncino-3.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2017-07-11-install-build-rokers-io.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2017-07-27-trying-espotek-labrador.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2017-08-08-cmdline-git-with-github-2fa.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2017-09-11-git-aware-prompt.md does not exist.
     Build Warning: Layout 'default' requested in about.html does not exist.
     Build Warning: Layout 'default' requested in test/index-FROM-JEKYLL.html does not exist.
     Build Warning: Layout 'home' requested in index.md does not exist.
                    done in 1.125 seconds.
 Auto-regeneration: enabled for '/home/gmacario/github/gmacario/gmacario.github.io'
Configuration file: /home/gmacario/github/gmacario/gmacario.github.io/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

I then browse <http://localhost:4000/> but all what I get is a blank page.

Any clues about what I might have forgotten?

**Comment by gmacario** [comment]
A quick Google search pointed me to https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/37

To be investigated. For the record, here is the version of Jeklyy I have installed with `sudo apt install jekyll`:

```
gmacario@itm-gmacario-w7:~/github/gmacario/gmacario.github.io (ludusrusso-master)$ dpkg -l jekyll
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                Version        Architecture   Description
+++-===================-==============-==============-===========================================
ii  jekyll              3.0.1+dfsg-1   all            Simple, blog aware, static site generator
gmacario@itm-gmacario-w7:~/github/gmacario/gmacario.github.io (ludusrusso-master)$ 
```

**Comment by ludusrusso** [comment]
Ciao,
you should install [Jekyll using `bundler`](https://jekyllrb.com/docs/quickstart/).

The run it with

```bash
blndle exec jekyll serve --safe
```

This should run Jekyll in a similar enviroment of GitHub Page!

This is my output!

schermata 2018-02-05 alle 08 28 55

**Comment by gmacario** [comment]
Installed Jekyll v. 3.6.2 using the following commands:

```shell
sudo apt update
sudo apt remove jekyll
sudo apt autoremove
sudo apt install ruby-bundler ruby-dev
sudo gem install ffi -v '1.9.18'
bundle install
```

When I run Jekyll

```shell
bundle exec jekyll serve --safe
```

I got the following error

```
gmacario@itm-gmacario-w7:~/github/gmacario/gmacario.github.io (ludusrusso-master)$ bundle exec jekyll serve --safe
Configuration file: /home/gmacario/github/gmacario/gmacario.github.io/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
            Source: /home/gmacario/github/gmacario/gmacario.github.io
       Destination: /home/gmacario/github/gmacario/gmacario.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (/var/lib/gems/2.3.0/gems/minima-2.3.0/_includes/head.html line 5): Unknown tag 'seo' included in /_layouts/default.html
jekyll 3.6.2 | Error:  Liquid syntax error (/var/lib/gems/2.3.0/gems/minima-2.3.0/_includes/head.html line 5): Unknown tag 'seo' included 
gmacario@itm-gmacario-w7:~/github/gmacario/gmacario.github.io (ludusrusso-master)$
```

**Comment by gmacario** [comment]
@ludusrusso could you please provide your result of the following command

```shell
bundle update
```

**Comment by gmacario** [comment]
I tried `jekyll serve` instead and got no errors:

```
gmacario@itm-gmacario-w7:~/github/gmacario/gmacario.github.io (ludusrusso-master)$ jekyll serve
Configuration file: /home/gmacario/github/gmacario/gmacario.github.io/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
            Source: /home/gmacario/github/gmacario/gmacario.github.io
       Destination: /home/gmacario/github/gmacario/gmacario.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 1.572 seconds.
 Auto-regeneration: enabled for '/home/gmacario/github/gmacario/gmacario.github.io'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```
Then browsing http://localhost:4000/

screenshot from 2018-02-06 19-54-55

LGTM, merging

**Pull request merged**
